### ISSUE TITLE
Release package bitmap format

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2MapImager#45]
The release package contains inconsistently formatted bitmap images. The first two seem to use the custom format, while the others use standard Windows bitmap format.

Crow commented about difficulties from this on IRC. I've verified this for release package 2.0.1.

Do the bitmaps even need to be part of the release package? Or perhaps, should they be included in the release package? I was a little surprised to see them in there on GitHub. I rather think it's not so appropriate to include them.

**Comment by Brett208** [comment]
I made a mistake by including them in the releases. Thanks for catching the problem. Not sure how the mixed well formats made it in besides that they should not have been added at all.

Updated the releases to no longer include the wells packaged.

I'm going to bump fixing getting a new release of this and OP2Archive above work on NetFixClient as people are using it and the bugs are probably annoying. Also, with this release the wells will just be pulled from the volume and it will eliminate need to find the bitmaps anywhere.

-Brett

**Comment by DanRStevens** [comment]
Alright, sounds good.

Did you check previous releases too? I didn't check them all, but the download sizes looked similar, so probably the same bitmap packaging.

Related, maybe the history of the project should be checked for accidental commits.

**Comment by Brett208** [comment]
Yes, both releases are good now. Didn't do a deep dive of the repository code.

-Brett
