### ISSUE TITLE
Determine Linux specific solution for FreeImage inclusion

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2MapImager#7]
It occurred to me that I don't know what the equivalent of a .dll is on Linux. @DanRStevens, did you have a recommendation on how to tackle including FreeImage on the Linux build? 

I remember looking into compiling FreeImage from source code for inclusion as being a bear using Visual Studio. Not sure how difficult this would be on Linux. 

-Brett

**Comment by DanRStevens** [comment]
The equivalent to a DLL is a "shared object" (.so).

I copied the makefile from the OP2Archive project into OP2MapImager. It naturally tried to recurse into the FreeImage folder and compile it. It got a few errors which look related to the include path. Not terribly surprising. Perhaps with an include path update, the makefile could be used largely as is, and just compile FreeImage from source.

Perhaps we can tackle this in the near future as just a simple include folder update and compile from source. Or maybe some settings can be changed to dynamically load a shared object file. I expect this to be a relatively small edit to the makefile, though it may take some reading to figure out what that small edit should be.

**Comment by Brett208** [comment]
FreeImage appears to be maintained as a CVS repository. https://sourceforge.net/p/freeimage/code/?source=navbar. I don't think we can include the sourcecode as a proper submodule since it is not in a Git repository?

I guess we could leave a directory called FreeImage in the root project directory with a link to the FreeImage repository for downloading.

I didn't see a .so file in the FreeImage downloads, so I'm guessing we would have to manually compile one if we went the dynamic library route. In generally it makes sense to switch to static compilation to me, but I'm also happy with the current solution since it is working.

-Brett

**Comment by DanRStevens** [comment]
Ok, there is a FreeImage development package for Ubuntu. That will install a pre-compiled library and associated header files to build against it.

```
sudo apt install libfreeimage-dev
```

In the makefile, I added an exclude to the `find` so it would ignore the example code in "FreeImage/" folder. This prevents compile errors trying to compile the example code:
```
SRCS := $(shell find $(SRCDIR) -name '*.cpp' -not -path './FreeImage/*')
```
I also added a reference to the "freeimage" library:
```
LDFLAGS := -lstdc++ -lm -lstdc++fs -lfreeimage
```

The code compiles with these settings. I'll submit the makefile in a new branch.

**Comment by Brett208** [comment]
Good news! Just curious, but does it also allow imaging a map for you, or is it just compiling?

This issue should have actually been 2 now that I think about it. One for getting things working on Linux and one for the long term FreeImage solution.

-Brett

**Comment by DanRStevens** [comment]
I only tried compiling, not running.

**Comment by DanRStevens** [comment]
We should probably close this issue now. We have a clear way to compile this project on Linux, and dynamically link to dependent libraries. Dependencies, such as FreeImage, will be installed using system specific methods, such as the Apt package manager on Ubuntu.
